authors = ["MartinuzziFrancesco <martinuzzi.francesco@gmail.com>"]
name = "ReservoirComputing"
uuid = "b0e6014a-3d0d-11ea-03a2-4de12a57c7be"
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
DifferentialEquations = "1f5d7977befe3265d9b7fc256d8f88d0bd9b6ffa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ParameterizedFunctions", "DifferentialEquations", "Plots"]

